title: Decode Doubt
description: एक सिंपल और शुरुआती के लिए बनी Jekyll थीम
baseurl: "" # उप-फोल्डर में हो तो /subfolder
url: "https://decodedoubt.github.io"
theme: minima
permalink: /:year/:month/:day/:title.html

plugins:
  - jekyll-sitemap
